# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bizpost',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
