# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
